### ISSUE TITLE
what if payment obj is null?

### ISSUE THREAD

**Issue by mrbln** [altrk19/Spring-Boot-Statemachine#1]
https://github.com/altrk19/Spring-Boot-Statemachine/blob/5f727f388a898530652aaf78a60648be2aff245d/Example01/src/main/java/guru/springframework/ssm/services/PaymentServiceImpl.java#L72

payment objesi null olursa NPE alma ihtimali var mıdır?

**Comment by altrk19** [comment]
haklısın, buraya bir null kontrolü gerekli :)
